name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
    #paths:
      #- 'Front-end/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - 'Front-end/**'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: Front-end

      - name: Clean build directory
        run: rm -rf Front-end/dist || true

      - name: Build Angular App
        run: npm run build -- --output-path=dist/test --configuration=production
        working-directory: Front-end

      - name: Verify build output
        run: ls -la Front-end/dist/test || echo "Directory not found"

      - name: Copy build files (if needed)
        run: |
          mkdir -p Front-end/dist/test
          cp -r Front-end/dist/* Front-end/dist/test/

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_HILL_06F5EC50F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./Front-end" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "Front-end/dist/test" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_HILL_06F5EC50F }}
          action: "close"
